# Generated by Django 5.2.1 on 2025-05-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('age_rating', models.CharField(max_length=5)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('director', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('age_rating', models.CharField(max_length=5)),
                ('seasons', models.IntegerField(default=1)),
                ('director', models.CharField(max_length=100)),
                ('is_ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('air_date', models.DateField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='watcharyApp.tvseries')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('series', 'season_number', 'episode_number')},
            },
        ),
    ]
